# Generated by Django 4.0.5 on 2022-08-19 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('person', 'person'), ('place', 'place'), ('resource', 'resource')], default='place', max_length=20)),
                ('has_price', models.BooleanField(default=True)),
                ('has_img_service', models.BooleanField(default=False)),
                ('has_description_service', models.BooleanField(default=False)),
                ('has_description_item', models.BooleanField(default=False)),
                ('has_large_number', models.BooleanField(default=False)),
                ('has_img_item', models.BooleanField(default=False)),
                ('has_email', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('theme', models.CharField(blank=True, choices=[('dark', 'dark'), ('light', 'light')], default='light', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
