# Generated by Django 4.0.5 on 2022-08-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='config',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
